Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 19
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 39
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 24
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 19
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 10
Traceback (most recent call last):
  File "benchmark_3d_overthrust.py", line 67, in <module>
    File("shots/a_true_velocity.pvd", comm=comm.comm).write(vp)
NameError: name 'File' is not defined
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 16
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 23178.4 ON n14 CANCELLED AT 2023-02-14T16:30:41 ***
slurmstepd: error: *** JOB 23178 ON n14 CANCELLED AT 2023-02-14T16:30:41 ***
