Traceback (most recent call last):
  File "benchmark_3d.py", line 109, in <module>
    meshio.write_points_cells(
  File "/home/public/app/firedrake_gnu_042022/firedrake/lib/python3.8/site-packages/meshio/_helpers.py", line 139, in write_points_cells
    mesh.write(filename, file_format=file_format, **kwargs)
  File "/home/public/app/firedrake_gnu_042022/firedrake/lib/python3.8/site-packages/meshio/_mesh.py", line 241, in write
    write(path_or_buf, self, file_format, **kwargs)
  File "/home/public/app/firedrake_gnu_042022/firedrake/lib/python3.8/site-packages/meshio/_helpers.py", line 177, in write
    if value.shape[1] != num_nodes_per_cell[key]:
IndexError: tuple index out of range
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 10
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 23173.2 ON n14 CANCELLED AT 2023-02-14T16:13:51 ***
slurmstepd: error: *** JOB 23173 ON n14 CANCELLED AT 2023-02-14T16:13:51 ***
